/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "error": "#ba1a1a",
        "tertiary": "#0053db",
        "on-tertiary-container": "#002771",
        "secondary": "#006c49",
        "on-error-container": "#93000a",
        "surface-container-highest": "#e2e2e6",
        "surface-container-lowest": "#ffffff",
        "on-primary-container": "#003521",
        "surface-tint": "#006c48",
        "surface": "#f9f9fd",
        "on-tertiary-fixed": "#00174b",
        "background": "#f9f9fd",
        "outline": "#6d7a71",
        "inverse-on-surface": "#f0f0f4",
        "secondary-container": "#96f2c4",
        "surface-container-low": "#f3f3f7",
        "secondary-fixed": "#99f5c6",
        "surface-bright": "#f9f9fd",
        "on-secondary-fixed": "#002113",
        "surface-dim": "#d9dade",
        "surface-container": "#ededf2",
        "primary": "#006c48",
        "surface-container-high": "#e8e8ec",
        "on-secondary": "#ffffff",
        "outline-variant": "#bccabf",
        "primary-fixed": "#7dfabe",
        "on-primary-fixed-variant": "#005235",
        "on-tertiary-fixed-variant": "#003ea8",
        "on-surface-variant": "#3d4a42",
        "error-container": "#ffdad6",
        "primary-container": "#19a974",
        "on-primary-fixed": "#002113",
        "on-background": "#1a1c1f",
        "surface-variant": "#e2e2e6",
        "on-secondary-container": "#00714c",
        "tertiary-fixed": "#dbe1ff",
        "secondary-fixed-dim": "#7dd9ab",
        "inverse-surface": "#2f3034",
        "tertiary-fixed-dim": "#b4c5ff",
        "on-primary": "#ffffff",
        "on-error": "#ffffff",
        "primary-fixed-dim": "#5fdda3",
        "on-surface": "#1a1c1f",
        "inverse-primary": "#5fdda3",
        "tertiary-container": "#688fff",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed-variant": "#005236"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "space-2xs": "0.125rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "0.75rem",
        "space-base": "1rem",
        "space-lg": "1.25rem",
        "space-xl": "1.5rem",
        "space-2xl": "2rem",
        "space-3xl": "2.5rem",
        "space-4xl": "3rem",
        "margin-mobile": "1rem",
        "margin-desktop": "2rem",
        "gutter-mobile": "0.75rem",
        "gutter-desktop": "1.25rem"
      },
      fontFamily: {
        "headline-lg": ["Geist", "sans-serif"],
        "headline-lg-mobile": ["Geist", "sans-serif"],
        "telemetry-hero": ["JetBrains Mono", "monospace"],
        "body-sm": ["Geist", "sans-serif"],
        "label-sm": ["JetBrains Mono", "monospace"],
        "label-md": ["Geist", "sans-serif"],
        "headline-md": ["Geist", "sans-serif"],
        "telemetry-hero-mobile": ["JetBrains Mono", "monospace"],
        "display": ["Geist", "sans-serif"],
        "headline-sm": ["Geist", "sans-serif"],
        "telemetry-sm": ["JetBrains Mono", "monospace"],
        "body-lg": ["Geist", "sans-serif"],
        "body-md": ["Geist", "sans-serif"],
        "telemetry-md": ["JetBrains Mono", "monospace"]
      },
      fontSize: {
        "headline-lg": ["2.25rem", { lineHeight: "1.2", letterSpacing: "-0.025em", fontWeight: "600" }],
        "headline-lg-mobile": ["1.75rem", { lineHeight: "1.25", letterSpacing: "-0.02em", fontWeight: "600" }],
        "telemetry-hero": ["2.5rem", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "500" }],
        "body-sm": ["0.75rem", { lineHeight: "1.4", letterSpacing: "0.005em", fontWeight: "400" }],
        "label-sm": ["0.6875rem", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "400" }],
        "label-md": ["0.75rem", { lineHeight: "1", letterSpacing: "0.04em", fontWeight: "500" }],
        "headline-md": ["1.5rem", { lineHeight: "1.3", letterSpacing: "-0.015em", fontWeight: "600" }],
        "telemetry-hero-mobile": ["2rem", { lineHeight: "1.15", letterSpacing: "-0.015em", fontWeight: "500" }],
        "display": ["3.5rem", { lineHeight: "1.1", letterSpacing: "-0.03em", fontWeight: "600" }],
        "headline-sm": ["1.125rem", { lineHeight: "1.4", letterSpacing: "-0.01em", fontWeight: "600" }],
        "telemetry-sm": ["0.8125rem", { lineHeight: "1.25", letterSpacing: "0em", fontWeight: "400" }],
        "body-lg": ["1rem", { lineHeight: "1.5", letterSpacing: "0em", fontWeight: "400" }],
        "body-md": ["0.875rem", { lineHeight: "1.45", letterSpacing: "0em", fontWeight: "400" }],
        "telemetry-md": ["1.125rem", { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "500" }]
      }
    }
  },
  plugins: []
}
